//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutilSrum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetScrumEntities : DbContext
    {
        public ProjetScrumEntities()
            : base("name=ProjetScrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Backlog> Backlogs { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<Sprint> Sprints { get; set; }
        public virtual DbSet<Tache> Taches { get; set; }
        public virtual DbSet<User_Story> User_Story { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
