//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutilSrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Story
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int Cost { get; set; }
        public int Priority { get; set; }
        public Nullable<int> Backlog_ID { get; set; }
        public Nullable<int> Sprint_ID { get; set; }
    
        public virtual Backlog Backlog { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
